steps:

  - name: golang:1.17
    entrypoint: /bin/bash
    args:
      - ./test.sh
    id: test

  - name: golang:1.17
    entrypoint: /bin/bash
    args:
      - ./build.sh
    id: build_app
    waitFor:
      - test

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      '$_REGISTRY',
      './tmp'
    ]
    id: build_image
    waitFor:
      - build_app

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      '$_REGISTRY',
    ]

substitutions:
  _REPO_NAME: my-repo
  _IMAGE_NAME: visit-card
  _REGISTRY: europe-central2-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_IMAGE_NAME:$SHORT_SHA

