steps:

  - name: golang:1.17
    entrypoint: /bin/bash
    args:
      - ./test.sh
    id: test

  - name: golang:1.17
    entrypoint: /bin/bash
    args:
      - ./build.sh
    id: build_app

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      '$_REGISTRY/$PROJECT_ID/$_REPO_NAME/$_APP_NAME:$SHORT_SHA',
      './tmp'
    ]
    id: build_image

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      '$_REGISTRY/$PROJECT_ID/$_REPO_NAME/$_APP_NAME:$SHORT_SHA',
    ]
    id: push_image

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '$_APP_NAME'
      - '--image'
      - '$_REGISTRY/$PROJECT_ID/$_REPO_NAME/$_APP_NAME:$SHORT_SHA'
      - '--region'
      - '$_APP_REGION'
    id: deploy

substitutions:
  _REPO_NAME: my-repo
  _REGISTRY: europe-central2-docker.pkg.dev
  _APP_NAME: visit-card
  _APP_REGION: europe-west1

