steps:

  - name: golang:1.17
    entrypoint: /bin/bash
    args:
      - go
      - test
      - -timeout
      - 1m
      - -v
      - ./...
    id: test

  - name: golang:1.17
    entrypoint: /bin/bash
    args:
      - ./build.sh
    id: build
    waitFor:
      - test

